trigger:
- main

variables:
  # Azure Subscription name
  azureSubscription: 'Microsoft Azure Sponsorship'

  # App Service name
  appServiceName: 'Your App Service Name'

  # Docker image tag
  dockerTag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: 'build'
        repository: 'ZenFlo'
        dockerfile: '**/Dockerfile'
        tags: '$(dockerTag)'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Login to Azure account'
      inputs:
        azureSubscription: '$(azureSubscription)'

    - task: AzureAppServiceContainer@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(appServiceName)'
        containerImage: 'your-registry-name.azurecr.io/your-repository-name:$(dockerTag)'
        startupCommand: 'uvicorn main:app --host 0.0.0.0 --port 80'
