# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - ZenFlo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip backend artifact for deployment
        run: zip backend-release.zip ./* -r

      - name: Zip frontend artifact for deployment
        run: zip frontend-release.zip ./Templates/index.html
        working-directory: ${{ github.workspace }}   # Assuming frontend files are in a 'Templates' directory

      - name: Upload backend artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: backend-release.zip

      - name: Upload frontend artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: frontend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend-app

      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend-app

      - name: Unzip backend artifact for deployment
        run: unzip backend-release.zip

      - name: Unzip frontend artifact for deployment
        run: unzip frontend-release.zip -d ./wwwroot   # Assuming wwwroot is the directory for frontend files in Azure App Service

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D24B79A05831435FBC2B29EBD57D4A83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4049A916FD94AB3B10338E2B5EC7F11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9EF1671D95E9442C9D76FF290926BBE0 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'ZenFlo'
          slot-name: 'Production'
